Repository gdgoc-konkuk/platform-core, pull requests merged in 2024-10, with the labels that each got.

#45 Chore : OCI Migration
  .github/actions/ci-workflow.yml
  .github/workflows/ci-workflow.yml
  .gitignore
  Dockerfile
  build.gradle
  build.sh
  compose.yaml
  nginx.conf
  sql/v0.sql
  src/main/java/gdsc/konkuk/platformcore/global/configs/SecurityConfig.java
  src/main/java/gdsc/konkuk/platformcore/global/consts/PlatformConstants.java
  src/main/resources/application-prod.yaml
Labels: size/XL

#46 chore : awslogs multline pattern 설정
  compose.yaml
Labels: enhancement, size/XS

#49 Fix : discord message sending
  src/main/java/gdsc/konkuk/platformcore/external/discord/DiscordClient.java
  src/main/java/gdsc/konkuk/platformcore/external/discord/DiscordEmbed.java
  src/main/java/gdsc/konkuk/platformcore/external/discord/DiscordMessage.java
  src/test/java/gdsc/konkuk/platformcore/external/discord/DiscordClientTest.java
Labels: bug, enhancement, size/M
