Repository gdgoc-konkuk/platform-core, pull requests merged in 2024-08, with the labels that each got.

#12 Bp 38 retrospect crud api implementation
  src/main/java/gdsc/konkuk/platformcore/application/event/EventService.java
  src/main/java/gdsc/konkuk/platformcore/controller/event/EventController.java
  src/main/java/gdsc/konkuk/platformcore/controller/event/EventRegisterRequest.java
  src/main/java/gdsc/konkuk/platformcore/controller/event/RetrospectUpdateRequest.java
  src/main/java/gdsc/konkuk/platformcore/domain/event/entity/Event.java
  src/main/java/gdsc/konkuk/platformcore/domain/event/entity/Retrospect.java
  src/test/java/gdsc/konkuk/platformcore/controller/email/EmailControllerTest.java
  src/test/java/gdsc/konkuk/platformcore/controller/event/EventControllerTest.java
Labels: feature

#15 Bp 39 implement email scheduler
  src/main/java/gdsc/konkuk/platformcore/application/email/EmailService.java
  src/main/java/gdsc/konkuk/platformcore/application/email/EmailTaskFacade.java
  src/main/java/gdsc/konkuk/platformcore/application/email/EmailTaskScheduler.java
  src/main/java/gdsc/konkuk/platformcore/controller/email/EmailController.java
  src/main/java/gdsc/konkuk/platformcore/domain/email/repository/EmailTaskRepository.java
  src/main/java/gdsc/konkuk/platformcore/external/discord/DiscordClient.java
  src/main/java/gdsc/konkuk/platformcore/external/discord/DiscordEmbed.java
  src/main/java/gdsc/konkuk/platformcore/external/discord/DiscordMessage.java
  src/main/java/gdsc/konkuk/platformcore/external/email/EmailClient.java
  src/main/java/gdsc/konkuk/platformcore/global/configs/RestTemplateConfig.java
  src/main/java/gdsc/konkuk/platformcore/global/configs/SchedulerConfig.java
  src/main/java/gdsc/konkuk/platformcore/global/consts/PlatformConstants.java
  src/main/java/gdsc/konkuk/platformcore/global/exceptions/GlobalErrorCode.java
  src/main/java/gdsc/konkuk/platformcore/global/exceptions/TaskNotFoundException.java
  src/main/java/gdsc/konkuk/platformcore/global/scheduler/TaskInMemoryRepository.java
  src/main/java/gdsc/konkuk/platformcore/global/scheduler/TaskScheduler.java
  src/test/java/gdsc/konkuk/platformcore/application/email/EmailIntegrationTest.java
  src/test/java/gdsc/konkuk/platformcore/application/email/EmailServiceTest.java
  src/test/java/gdsc/konkuk/platformcore/application/email/EmailTaskFacadeTest.java
  src/test/java/gdsc/konkuk/platformcore/controller/email/EmailControllerTest.java
  src/test/java/gdsc/konkuk/platformcore/external/discord/DiscordClientTest.java
  src/test/java/gdsc/konkuk/platformcore/external/discord/DiscordMessageTest.java
Labels: enhancement

#16 fix : 이메일 저장후 바로 조회 시 조회가 안되는 이슈 수정
  src/main/java/gdsc/konkuk/platformcore/application/email/EmailService.java
  src/main/java/gdsc/konkuk/platformcore/application/email/EmailTaskScheduler.java
  src/main/java/gdsc/konkuk/platformcore/external/discord/DiscordClient.java
  src/test/java/gdsc/konkuk/platformcore/application/email/EmailServiceTest.java
Labels: bug

#13 Bp 37 event crud api implementation
  build.gradle
  src/main/java/gdsc/konkuk/platformcore/application/event/EventBrief.java
  src/main/java/gdsc/konkuk/platformcore/application/event/EventMapper.java
  src/main/java/gdsc/konkuk/platformcore/application/event/EventService.java
  src/main/java/gdsc/konkuk/platformcore/application/event/EventWithAttendance.java
  src/main/java/gdsc/konkuk/platformcore/application/member/MemberAttendanceInfo.java
  src/main/java/gdsc/konkuk/platformcore/controller/attendance/AttendanceController.java
  src/main/java/gdsc/konkuk/platformcore/controller/event/EventBriefResponse.java
  src/main/java/gdsc/konkuk/platformcore/controller/event/EventController.java
  src/main/java/gdsc/konkuk/platformcore/controller/event/EventDetailResponse.java
  src/main/java/gdsc/konkuk/platformcore/controller/event/EventRegisterRequest.java
  src/main/java/gdsc/konkuk/platformcore/controller/event/EventUpdateRequest.java
  src/main/java/gdsc/konkuk/platformcore/domain/event/entity/Event.java
  src/main/java/gdsc/konkuk/platformcore/domain/event/entity/EventImage.java
  src/main/java/gdsc/konkuk/platformcore/domain/event/entity/Retrospect.java
  src/main/java/gdsc/konkuk/platformcore/domain/event/repository/EventRepository.java
  src/main/java/gdsc/konkuk/platformcore/domain/member/entity/Member.java
  src/main/java/gdsc/konkuk/platformcore/external/s3/S3Properties.java
  src/main/java/gdsc/konkuk/platformcore/external/s3/StorageClient.java
  src/main/java/gdsc/konkuk/platformcore/global/configs/SecurityConfig.java
  src/main/java/gdsc/konkuk/platformcore/global/utils/FileValidator.java
  src/test/java/gdsc/konkuk/platformcore/application/email/EmailServiceHelperTest.java
  src/test/java/gdsc/konkuk/platformcore/controller/attendance/AttendanceControllerTest.java
  src/test/java/gdsc/konkuk/platformcore/controller/email/EmailControllerTest.java
  src/test/java/gdsc/konkuk/platformcore/controller/event/EventControllerTest.java
  src/test/java/gdsc/konkuk/platformcore/controller/member/MemberControllerTest.java
Labels: feature

#17 Fix redefine email receivers
  src/main/java/gdsc/konkuk/platformcore/application/email/EmailTaskScheduler.java
  src/main/java/gdsc/konkuk/platformcore/domain/email/entity/EmailReceivers.java
  src/main/java/gdsc/konkuk/platformcore/external/discord/DiscordClient.java
  src/test/java/gdsc/konkuk/platformcore/external/discord/DiscordClientTest.java
Labels: bug

#18 Fix: 로그인 성공 후 스태틱 페이지가 없어 발생하는 에러 수정
  src/main/java/gdsc/konkuk/platformcore/application/auth/CustomAuthenticationSuccessHandler.java
  src/test/java/gdsc/konkuk/platformcore/controller/auth/AuthControllerTest.java
Labels: bug

#21 Fix: error response
  src/main/java/gdsc/konkuk/platformcore/global/controller/GlobalExceptionHandler.java
  src/main/java/gdsc/konkuk/platformcore/global/exceptions/BusinessException.java
  src/main/java/gdsc/konkuk/platformcore/global/exceptions/GlobalErrorCode.java
Labels: bug

#20 Fix jpa element collection type
  src/main/java/gdsc/konkuk/platformcore/application/email/EmailService.java
  src/main/java/gdsc/konkuk/platformcore/controller/email/dto/EmailSendRequest.java
  src/main/java/gdsc/konkuk/platformcore/controller/email/dto/EmailTaskDetailsResponse.java
  src/main/java/gdsc/konkuk/platformcore/domain/email/entity/EmailReceivers.java
  src/main/java/gdsc/konkuk/platformcore/domain/email/entity/EmailTask.java
  src/main/java/gdsc/konkuk/platformcore/external/email/EmailClient.java
  src/test/java/gdsc/konkuk/platformcore/annotation/CustomMockUser.java
  src/test/java/gdsc/konkuk/platformcore/annotation/RestDocsTest.java
  src/test/java/gdsc/konkuk/platformcore/annotation/WithMyCustomUserSecurityContextFactory.java
  src/test/java/gdsc/konkuk/platformcore/application/email/EmailIntegrationTest.java
  src/test/java/gdsc/konkuk/platformcore/application/email/EmailServiceHelperTest.java
  src/test/java/gdsc/konkuk/platformcore/application/email/EmailServiceTest.java
  src/test/java/gdsc/konkuk/platformcore/application/email/EmailTaskFacadeTest.java
  src/test/java/gdsc/konkuk/platformcore/application/member/MemberServiceTest.java
  src/test/java/gdsc/konkuk/platformcore/controller/attendance/AttendanceControllerTest.java
  src/test/java/gdsc/konkuk/platformcore/controller/auth/AuthControllerTest.java
  src/test/java/gdsc/konkuk/platformcore/controller/email/EmailControllerTest.java
  src/test/java/gdsc/konkuk/platformcore/controller/event/EventControllerTest.java
  src/test/java/gdsc/konkuk/platformcore/controller/member/MemberControllerTest.java
  src/test/java/gdsc/konkuk/platformcore/domain/email/entity/EmailTaskTest.java
  src/test/java/gdsc/konkuk/platformcore/external/discord/DiscordClientTest.java
  src/test/java/gdsc/konkuk/platformcore/external/email/EmailClientTest.java
Labels: bug, enhancement

#28 Refactor attendance api
  Dockerfile
  build.sh
  src/main/java/gdsc/konkuk/platformcore/application/attendance/AttendanceService.java
  src/main/java/gdsc/konkuk/platformcore/application/attendance/AttendanceServiceHelper.java
  src/main/java/gdsc/konkuk/platformcore/application/attendance/ParticipantMapper.java
  src/main/java/gdsc/konkuk/platformcore/application/attendance/dtos/MemberAttendanceInfo.java
  src/main/java/gdsc/konkuk/platformcore/application/attendance/dtos/MemberAttendanceQueryDto.java
  src/main/java/gdsc/konkuk/platformcore/application/member/MemberAttendanceInfo.java
  src/main/java/gdsc/konkuk/platformcore/application/member/MemberService.java
  src/main/java/gdsc/konkuk/platformcore/application/member/dtos/MemberAttendances.java
  src/main/java/gdsc/konkuk/platformcore/controller/attendance/AttendanceController.java
  src/main/java/gdsc/konkuk/platformcore/controller/attendance/dtos/AttendSuccessDto.java
  src/main/java/gdsc/konkuk/platformcore/controller/member/AttendanceUpdateInfo.java
  src/main/java/gdsc/konkuk/platformcore/controller/member/MemberController.java
  src/main/java/gdsc/konkuk/platformcore/domain/attendance/entity/Attendance.java
  src/main/java/gdsc/konkuk/platformcore/domain/attendance/entity/Participant.java
  src/main/java/gdsc/konkuk/platformcore/domain/attendance/repository/AttendanceRepository.java
  src/main/java/gdsc/konkuk/platformcore/domain/attendance/repository/ParticipantRepository.java
  src/test/java/gdsc/konkuk/platformcore/controller/attendance/AttendanceControllerTest.java
  src/test/java/gdsc/konkuk/platformcore/controller/member/MemberControllerTest.java
  src/test/java/gdsc/konkuk/platformcore/domain/attendance/entity/AttendanceTest.java
Labels: enhancement

#30 Feat: Event 삭제 API
  src/main/java/gdsc/konkuk/platformcore/application/event/EventMapper.java
  src/main/java/gdsc/konkuk/platformcore/application/event/EventService.java
  src/main/java/gdsc/konkuk/platformcore/controller/event/EventController.java
  src/test/java/gdsc/konkuk/platformcore/controller/event/EventControllerTest.java
Labels: feature

#31 Feat: include receiver name into mail registration
  src/main/java/gdsc/konkuk/platformcore/application/email/EmailService.java
  src/main/java/gdsc/konkuk/platformcore/controller/email/dtos/EmailReceiverInfo.java
  src/main/java/gdsc/konkuk/platformcore/controller/email/dtos/EmailSendRequest.java
  src/main/java/gdsc/konkuk/platformcore/controller/email/dtos/EmailTaskDetailsResponse.java
  src/main/java/gdsc/konkuk/platformcore/controller/email/dtos/SimpleEmailTaskResponse.java
  src/main/java/gdsc/konkuk/platformcore/domain/email/entity/EmailReceiver.java
  src/main/java/gdsc/konkuk/platformcore/domain/email/entity/EmailReceivers.java
  src/main/java/gdsc/konkuk/platformcore/domain/email/entity/EmailTask.java
  src/main/java/gdsc/konkuk/platformcore/external/email/EmailClient.java
  src/main/java/gdsc/konkuk/platformcore/global/consts/PlatformConstants.java
  src/test/java/gdsc/konkuk/platformcore/application/email/EmailIntegrationTest.java
  src/test/java/gdsc/konkuk/platformcore/application/email/EmailServiceHelperTest.java
  src/test/java/gdsc/konkuk/platformcore/application/email/EmailServiceTest.java
  src/test/java/gdsc/konkuk/platformcore/application/email/EmailTaskFacadeTest.java
  src/test/java/gdsc/konkuk/platformcore/controller/email/EmailControllerTest.java
  src/test/java/gdsc/konkuk/platformcore/domain/email/entity/EmailTaskTest.java
  src/test/java/gdsc/konkuk/platformcore/external/email/EmailClientTest.java
Labels: feature

#38 Test: use fixture
  build.gradle
  src/main/java/gdsc/konkuk/platformcore/controller/attendance/AttendanceController.java
  src/main/java/gdsc/konkuk/platformcore/controller/attendance/dtos/AttendSuccessResponse.java
  src/main/java/gdsc/konkuk/platformcore/controller/email/EmailController.java
  src/main/java/gdsc/konkuk/platformcore/controller/email/dtos/EmailSendRequest.java
  src/main/java/gdsc/konkuk/platformcore/controller/email/dtos/EmailTaskDetailResponse.java
  src/main/java/gdsc/konkuk/platformcore/controller/email/dtos/SimpleEmailTaskResponse.java
  src/main/java/gdsc/konkuk/platformcore/controller/email/mapper/EmailTaskMapper.java
  src/main/java/gdsc/konkuk/platformcore/controller/member/dtos/MemberRegisterRequest.java
  src/main/java/gdsc/konkuk/platformcore/domain/email/entity/EmailDetail.java
  src/main/java/gdsc/konkuk/platformcore/domain/email/entity/EmailTask.java
  src/main/java/gdsc/konkuk/platformcore/domain/member/entity/Member.java
  src/main/java/gdsc/konkuk/platformcore/domain/member/entity/MemberRole.java
  src/main/java/gdsc/konkuk/platformcore/external/email/EmailClient.java
  src/main/java/gdsc/konkuk/platformcore/global/utils/GetDefault.java
  src/test/java/gdsc/konkuk/platformcore/annotation/WithCustomUser.java
  src/test/java/gdsc/konkuk/platformcore/annotation/WithCustomUserSecurityContextFactory.java
  src/test/java/gdsc/konkuk/platformcore/application/email/EmailIntegrationTest.java
  src/test/java/gdsc/konkuk/platformcore/application/email/EmailServiceHelperTest.java
  src/test/java/gdsc/konkuk/platformcore/application/email/EmailServiceTest.java
  src/test/java/gdsc/konkuk/platformcore/application/email/EmailTaskFacadeTest.java
  src/test/java/gdsc/konkuk/platformcore/application/member/MemberServiceTest.java
  src/test/java/gdsc/konkuk/platformcore/controller/attendance/AttendanceControllerTest.java
  src/test/java/gdsc/konkuk/platformcore/controller/auth/AuthControllerTest.java
  src/test/java/gdsc/konkuk/platformcore/controller/email/EmailControllerTest.java
  src/test/java/gdsc/konkuk/platformcore/controller/event/EventControllerTest.java
  src/test/java/gdsc/konkuk/platformcore/controller/member/MemberControllerTest.java
  src/test/java/gdsc/konkuk/platformcore/domain/attendance/entity/AttendanceTest.java
  src/test/java/gdsc/konkuk/platformcore/domain/email/entity/EmailTaskTest.java
  src/test/java/gdsc/konkuk/platformcore/external/email/EmailClientTest.java
  src/test/java/gdsc/konkuk/platformcore/fixture/attendance/AttendanceFixture.java
  src/test/java/gdsc/konkuk/platformcore/fixture/attendance/AttendanceRegisterRequestFixture.java
  src/test/java/gdsc/konkuk/platformcore/fixture/attendance/ParticipantFixture.java
  src/test/java/gdsc/konkuk/platformcore/fixture/email/EmailDetailFixture.java
  src/test/java/gdsc/konkuk/platformcore/fixture/email/EmailReceiverFixture.java
  src/test/java/gdsc/konkuk/platformcore/fixture/email/EmailReceiverInfosFixture.java
  src/test/java/gdsc/konkuk/platformcore/fixture/email/EmailSendRequestFixture.java
  src/test/java/gdsc/konkuk/platformcore/fixture/email/EmailTaskFixture.java
  src/test/java/gdsc/konkuk/platformcore/fixture/event/EventBriefResponseFixture.java
  src/test/java/gdsc/konkuk/platformcore/fixture/event/EventFixture.java
  src/test/java/gdsc/konkuk/platformcore/fixture/event/EventImageFixture.java
  src/test/java/gdsc/konkuk/platformcore/fixture/event/EventRegisterRequestFixture.java
  src/test/java/gdsc/konkuk/platformcore/fixture/event/EventUpdateRequestFixture.java
  src/test/java/gdsc/konkuk/platformcore/fixture/event/EventWithAttendanceFixture.java
  src/test/java/gdsc/konkuk/platformcore/fixture/member/MemberAttendancesFixture.java
  src/test/java/gdsc/konkuk/platformcore/fixture/member/MemberFixture.java
  src/test/java/gdsc/konkuk/platformcore/fixture/member/MemberRegisterRequestFixture.java
Labels: enhancement
