Repository gdgoc-konkuk/platform-core, pull requests merged in 2025-07, with the labels that each got.

#84 [Refactor/email receiver to entity] - 엔티티 수정
  sql/v1_1.sql
  src/main/java/gdsc/konkuk/platformcore/application/email/EmailService.java
  src/main/java/gdsc/konkuk/platformcore/application/email/EmailTaskFacade.java
  src/main/java/gdsc/konkuk/platformcore/application/email/EmailTaskScheduler.java
  src/main/java/gdsc/konkuk/platformcore/application/email/dtos/EmailReceiverInfo.java
  src/main/java/gdsc/konkuk/platformcore/application/email/dtos/EmailTaskInfo.java
  src/main/java/gdsc/konkuk/platformcore/application/email/dtos/EmailTaskUpsertCommand.java
  src/main/java/gdsc/konkuk/platformcore/application/email/dtos/SimpleEmailTaskResponse.java
  src/main/java/gdsc/konkuk/platformcore/application/email/mapper/EmailTaskMapper.java
  src/main/java/gdsc/konkuk/platformcore/controller/email/dtos/EmailSendRequest.java
  src/main/java/gdsc/konkuk/platformcore/domain/email/entity/EmailReceiver.java
  src/main/java/gdsc/konkuk/platformcore/domain/email/entity/EmailReceivers.java
  src/main/java/gdsc/konkuk/platformcore/domain/email/entity/EmailSendStatus.java
  src/main/java/gdsc/konkuk/platformcore/domain/email/entity/EmailTask.java
  src/main/java/gdsc/konkuk/platformcore/domain/email/repository/EmailReceiverRepository.java
  src/main/java/gdsc/konkuk/platformcore/external/email/EmailClient.java
  src/test/java/gdsc/konkuk/platformcore/application/email/EmailIntegrationTest.java
  src/test/java/gdsc/konkuk/platformcore/application/email/EmailServiceTest.java
  src/test/java/gdsc/konkuk/platformcore/controller/email/EmailControllerTest.java
  src/test/java/gdsc/konkuk/platformcore/domain/email/entity/EmailTaskTest.java
  src/test/java/gdsc/konkuk/platformcore/external/email/EmailClientTest.java
  src/test/java/gdsc/konkuk/platformcore/util/fixture/email/EmailReceiverFixture.java
  src/test/java/gdsc/konkuk/platformcore/util/fixture/email/EmailTaskFixture.java
Labels: :chart_with_upwards_trend: enhancement, :rocket: feature, size/XL

#87 [Fix] cicd workflow 시퀀스 추가
  .github/workflows/cicd-workflow.yml
  .gitignore
Labels: size/XS

#90 [Fix] Oracle ATP 전환 및 CI/CD 개선 (SSL 인증서, Wallet 볼륨, Compose 수정)
  .github/workflows/cicd-workflow.yml
  compose.yaml
  nginx.conf
Labels: size/M

#91 [Fix] - cicd 중 docker compose build 단계에서 사용할 임시 값 지정
  compose.yaml
Labels: size/XS

#93 chore: DB Migration Ver 2.0
  sql/v2.sql
Labels: size/M

#94 [Chore] - Cicd workflow 수정
  .github/workflows/cicd-workflow.yml
  compose.yaml
Labels: size/S
