Repository gdgoc-konkuk/platform-core, pull requests merged in 2025-01, with the labels that each got.

#64 [Fix] Set Login Redirection
  src/main/java/gdsc/konkuk/platformcore/application/auth/CustomAuthenticationSuccessHandler.java
  src/main/java/gdsc/konkuk/platformcore/controller/attendance/AttendanceController.java
  src/main/java/gdsc/konkuk/platformcore/external/discord/DiscordMessage.java
  src/main/java/gdsc/konkuk/platformcore/global/consts/DiscordConstants.java
  src/main/java/gdsc/konkuk/platformcore/global/consts/PlatformConstants.java
  src/main/java/gdsc/konkuk/platformcore/global/consts/SPAConstants.java
  src/test/java/gdsc/konkuk/platformcore/external/discord/DiscordMessageTest.java
Labels: bug, enhancement, size/M

#67 [fix] move jwt to fragment
  src/main/java/gdsc/konkuk/platformcore/application/auth/CustomAuthenticationSuccessHandler.java
Labels: enhancement, size/XS

#69 [Refactor] fetching member attendances
  src/main/java/gdsc/konkuk/platformcore/application/attendance/dtos/MemberAttendanceInfo.java
  src/main/java/gdsc/konkuk/platformcore/application/member/MemberAttendanceAggregator.java
  src/main/java/gdsc/konkuk/platformcore/application/member/MemberFinder.java
  src/main/java/gdsc/konkuk/platformcore/application/member/MemberService.java
  src/main/java/gdsc/konkuk/platformcore/application/member/dtos/AttendanceUpdateCommand.java
  src/main/java/gdsc/konkuk/platformcore/application/member/dtos/MemberAttendanceAggregate.java
  src/main/java/gdsc/konkuk/platformcore/application/member/dtos/MemberAttendanceInfos.java
  src/main/java/gdsc/konkuk/platformcore/application/member/dtos/MemberAttendances.java
  src/main/java/gdsc/konkuk/platformcore/application/member/dtos/MemberCreateCommand.java
  src/main/java/gdsc/konkuk/platformcore/controller/member/MemberController.java
  src/main/java/gdsc/konkuk/platformcore/controller/member/dtos/AttendanceUpdateRequest.java
  src/main/java/gdsc/konkuk/platformcore/controller/member/dtos/MemberRegisterRequest.java
  src/main/java/gdsc/konkuk/platformcore/controller/member/dtos/MemberUpdateRequest.java
  src/test/java/gdsc/konkuk/platformcore/application/member/MemberFinderTest.java
  src/test/java/gdsc/konkuk/platformcore/application/member/MemberServiceTest.java
  src/test/java/gdsc/konkuk/platformcore/controller/member/MemberControllerTest.java
  src/test/java/gdsc/konkuk/platformcore/fixture/member/MemberAttendancesFixture.java
Labels: enhancement, size/XL

#71 Fix/remove processed email tasks
  src/main/java/gdsc/konkuk/platformcore/application/email/EmailService.java
  src/main/java/gdsc/konkuk/platformcore/application/email/EmailTaskFacade.java
  src/main/java/gdsc/konkuk/platformcore/application/email/EmailTaskScheduler.java
  src/main/java/gdsc/konkuk/platformcore/controller/email/EmailController.java
  src/test/java/gdsc/konkuk/platformcore/application/email/EmailIntegrationTest.java
  src/test/java/gdsc/konkuk/platformcore/application/email/EmailServiceTest.java
  src/test/java/gdsc/konkuk/platformcore/application/email/EmailTaskFacadeTest.java
  src/test/java/gdsc/konkuk/platformcore/controller/email/EmailControllerTest.java
Labels: bug, enhancement, size/M
